### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by clener** [clener/picky#1]
## Front-end

- [ ] needs to include username/email and password fields
- [ ] option to sign up if user is not a member yet
- [ ] login page has a title
- [ ] button to submit

## Back-end

- [ ] check if all fields are filled in and if they contain valid characters (alphanumeric and `-`, `_`)
- [ ] verify whether username exists and if it does check if it matches the encrypted password
- [ ] return response to front-end

### Visual Reference
![image](https://user-images.githubusercontent.com/21315707/27246144-a3fab864-52bd-11e7-9f1e-025319210d07.png)
