### ISSUE TITLE
Sign Up Screen

### ISSUE THREAD

**Issue by clener** [clener/picky#2]
## Front-End
- [ ] include title
- [ ] include username, email and password boxes
- [ ] include submit button

## Back-End
- [ ] check if username or email already exist and notify the user accordingly
- [ ] verify characters are allowed characters and that password is at least 6 characters in length
- [ ] save username, email and password
