### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by clener** [clener/picky#3]
## Front-End
- [ ] Timer to display how much time is left until submission date
- [ ] Display Listview with all items for the week
- [ ] include checkboxes for each items
- [ ] include submit button

## Back-End
- [ ] sort all requests to match the budget
- More to come soon...
